const fs = require('fs');
const path = require('path');
const { getLogPath } = require('../lib/journal');

async function planAtris(userInput = null) {
  const { loadConfig } = require('../utils/config');
  const { loadCredentials } = require('../utils/auth');
  const { executeCodeExecution } = require('../utils/claude_sdk');
  const args = process.argv.slice(3);
  const executeFlag = args.includes('--execute');
  const showFull = args.includes('--full') || args.includes('--verbose');
  
  const config = loadConfig();
  const executionMode = executeFlag ? 'agent' : (config.execution_mode || 'prompt');
  
  const targetDir = path.join(process.cwd(), 'atris');
  const navigatorFile = path.join(targetDir, 'agent_team', 'navigator.md');
  const personaPath = path.join(targetDir, 'PERSONA.md');
  const mapFilePath = path.join(targetDir, 'MAP.md');
  const featuresReadmePath = path.join(targetDir, 'features', 'README.md');

  if (!fs.existsSync(navigatorFile)) {
    console.log('✗ navigator.md not found. Run "atris init" first.');
    process.exit(1);
  }

  // Read navigator.md
  const navigatorSpec = fs.readFileSync(navigatorFile, 'utf8');

  // Read journal Inbox for context
  const { logFile } = getLogPath();
  let inboxContext = '';

  if (fs.existsSync(logFile)) {
    const logContent = fs.readFileSync(logFile, 'utf8');
    const inboxMatch = logContent.match(/## Inbox\n([\s\S]*?)(?=\n##|$)/);
    if (inboxMatch && inboxMatch[1].trim()) {
      inboxContext = inboxMatch[1].trim();
    }
  }

  // Read TODO.md (or legacy TASK_CONTEXTS.md) for current state
  const todoFile = path.join(targetDir, 'TODO.md');
  const legacyTaskContextsFile = path.join(targetDir, 'TASK_CONTEXTS.md');
  let taskContexts = '';
  const taskFilePath = fs.existsSync(todoFile)
    ? todoFile
    : (fs.existsSync(legacyTaskContextsFile) ? legacyTaskContextsFile : null);
  if (taskFilePath) {
    taskContexts = fs.readFileSync(taskFilePath, 'utf8');
  }

  // Detect uncertainty in inbox context (or direct user input)
  const uncertaintySignals = ['not sure', 'maybe', 'but ', 'thinking about', 'uncertain', 'unclear', 'unsure', 'don\'t know'];
  const combinedContext = [userInput, inboxContext].filter(Boolean).join('\n');
  const hasUncertainty = combinedContext && uncertaintySignals.some(signal =>
    combinedContext.toLowerCase().includes(signal)
  );

  const taskSourcePath = taskFilePath ? path.relative(process.cwd(), taskFilePath) : null;
  const journalPath = path.relative(process.cwd(), logFile);
  const navigatorPath = path.relative(process.cwd(), navigatorFile);
  const personaFileRef = fs.existsSync(personaPath) ? path.relative(process.cwd(), personaPath) : null;
  const mapFileRef = fs.existsSync(mapFilePath) ? path.relative(process.cwd(), mapFilePath) : null;
  const featuresReadmeRef = fs.existsSync(featuresReadmePath) ? path.relative(process.cwd(), featuresReadmePath) : null;
  const mapIsPlaceholder = (() => {
    if (!fs.existsSync(mapFilePath)) return false;
    try {
      const content = fs.readFileSync(mapFilePath, 'utf8').toLowerCase();
      return content.includes('generated by your ai agent after reading atris.md')
        || content.includes('run your ai agent with atris.md to populate this file');
    } catch {
      return false;
    }
  })();
  const inboxCount = inboxContext
    ? inboxContext
        .split('\n')
        .filter((line) => line.trim().startsWith('-'))
        .length
    : 0;

  console.log('');
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│ Atris Plan — Navigator Agent Activated                      │');
  console.log('└─────────────────────────────────────────────────────────────┘');
  console.log('');

  // Show suggestion if uncertainty detected
  if (hasUncertainty) {
    console.log('💡 Suggestion:');
    console.log('   Sounds like you\'re exploring options.');
    console.log('   Try `atris brainstorm` first for conversational exploration,');
    console.log('   then run `atris plan` when ready to commit.');
    console.log('');
    console.log('   Or continue with plan if you prefer. Your call.');
    console.log('');
    console.log('─────────────────────────────────────────────────────────────');
    console.log('');
  }

  if (userInput) {
    console.log('🎯 DIRECT REQUEST:');
    console.log('─────────────────────────────────────────────────────────────');
    console.log(userInput);
    console.log('');
    console.log('─────────────────────────────────────────────────────────────');
    console.log('');
  }
  console.log('📁 CONTEXT FILES (agent should read):');
  console.log(`- Navigator spec: ${navigatorPath}`);
  console.log(`- Persona: ${personaFileRef || 'atris/PERSONA.md (missing)'}`);
  const mapDisplay = mapFileRef
    ? `${mapFileRef}${mapIsPlaceholder ? ' (placeholder — generate first)' : ''}`
    : 'atris/MAP.md (missing)';
  console.log(`- MAP: ${mapDisplay}`);
  console.log(`- TODO: ${taskSourcePath || 'atris/TODO.md (missing)'}`);
  console.log(`- Features index: ${featuresReadmeRef || 'atris/features/README.md (missing)'}`);
  console.log(`- Journal (today): ${journalPath}`);
  console.log('');
  console.log(`📥 Inbox items: ${inboxCount}`);
  console.log('');

  if (showFull) {
    console.log('📋 NAVIGATOR SPEC (full):');
    console.log('─────────────────────────────────────────────────────────────');
    console.log(navigatorSpec);
    console.log('');
    console.log('📥 INBOX CONTEXT (full):');
    console.log('─────────────────────────────────────────────────────────────');
    console.log(inboxContext || '(No items in Inbox)');
    console.log('');
    console.log('📝 TODO.md (full):');
    console.log('─────────────────────────────────────────────────────────────');
    console.log(taskContexts || '(No TODO content)');
    console.log('');
  }

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📋 COPY/PASTE PROMPT FOR YOUR CODING AGENT:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('');
  console.log('You are the Navigator.');
  console.log('');
  console.log('Read these files:');
  console.log(`- ${navigatorPath}`);
  if (personaFileRef) console.log(`- ${personaFileRef}`);
  if (mapFileRef) console.log(`- ${mapFileRef}`);
  if (taskSourcePath) console.log(`- ${taskSourcePath}`);
  if (featuresReadmeRef) console.log(`- ${featuresReadmeRef}`);
  console.log(`- ${journalPath}`);
  console.log('');
  if (!mapFileRef || mapIsPlaceholder) {
    console.log('Note: If `atris/MAP.md` is missing or placeholder, generate it from `atris/atris.md` before writing tasks.');
    console.log('');
  }
  if (userInput) {
    console.log('Direct request:');
    console.log(userInput);
    console.log('');
  }
  console.log('Workflow:');
  console.log('1) ASCII visualize + wait for approval');
  console.log('2) Write plan artifacts: feature idea/build (+ validate) OR TODO Backlog');
  console.log('3) Stop. Do NOT execute (run `atris do` to build).');
  console.log('');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('💡 After planning: Run "atris do" to execute the build');
  if (!showFull) {
    console.log('   Tip: `atris plan --full` prints full spec/context for copy/paste.');
  }
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('');
  
  // Check execution mode
  if (executionMode === 'agent') {
    // Agent mode: execute via backend API
    if (!config.agent_id) {
      throw new Error('No agent selected. Run "atris agent" first.');
    }
    const credentials = loadCredentials();
    if (!credentials || !credentials.token) {
      throw new Error('Not logged in. Run "atris login" first.');
    }

    // Build system prompt
    let systemPrompt = '';
    if (navigatorSpec) {
      systemPrompt += navigatorSpec + '\n\n';
    }
    
    // Reference MAP.md and PERSONA.md
    if (fs.existsSync(personaPath)) {
      systemPrompt += '## PERSONA.md\n' + fs.readFileSync(personaPath, 'utf8') + '\n\n';
    }
    
    if (mapFileRef) {
      systemPrompt += `## MAP.md\nRead this file for file:line references: ${mapFileRef}\n\n`;
    }

    // Build user prompt with context
    let userPrompt = `You are the Navigator. Take ideas from Inbox → break them down into perfect, manageable tasks.\n\n`;
    userPrompt += `⚠️ CRITICAL: You MUST create visualizations BEFORE writing tasks!\n\n`;
    
    if (userInput) {
      userPrompt += `## DIRECT REQUEST:\n${userInput}\n\n`;
    }

    if (inboxContext) {
      userPrompt += `## INBOX CONTEXT:\n${inboxContext}\n\n`;
    } else {
      userPrompt += `## INBOX CONTEXT:\n(No items in Inbox - check logs/YYYY/YYYY-MM-DD.md for inbox items)\n\n`;
    }
    
    if (taskContexts) {
      userPrompt += `## CURRENT TODO.md:\n${taskContexts}\n\n`;
    }
    
    userPrompt += `Your job (execute these steps):\n\n`;
    userPrompt += `STEP 1: Generate ASCII visualizations for user approval\n`;
    userPrompt += `   Create diagrams showing architecture, flows, schemas, UI/UX.\n`;
    userPrompt += `   SHOW these diagrams and wait for approval before proceeding.\n\n`;
    userPrompt += `STEP 2: Break approved ideas into concrete tasks\n`;
    userPrompt += `   - Each task should be: Specific, Measurable, Actionable\n`;
    userPrompt += `   - Include file:line references from MAP.md\n`;
    userPrompt += `   - List dependencies between tasks\n`;
    userPrompt += `   - Add acceptance criteria for each task\n\n`;
    userPrompt += `STEP 3: Write tasks to TODO.md\n`;
    userPrompt += `   - Add tasks to Backlog section\n`;
    userPrompt += `   - Format: Task number, description, file refs, acceptance criteria\n`;
    userPrompt += `   - Quality over speed - tasks must be perfect for systems player execution\n\n`;
    userPrompt += `STEP 4: Create Validation Artifact (validate.md)\n`;
    userPrompt += `   - You MUST create a validate.md file for the feature.\n`;
    userPrompt += `   - This file acts as the executable simulation script for the Validator.\n`;
    userPrompt += `   - Include verifiable steps (e.g., 'Run curl...', 'Check DB...').\n\n`;
    userPrompt += `Start planning now. Read MAP.md for file references.`;

    console.log('');
    console.log('🤖 AGENT MODE: Executing via backend API...');
    console.log('');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    // Execute via API
    try {
      await executeCodeExecution({
        prompt: userPrompt,
        allowedTools: ['Read', 'Write', 'Edit'], // Navigator needs to write TODO.md
        permissionMode: 'default',
        maxTurns: 15,
        systemPrompt,
        workingDirectory: process.cwd(),
        agentId: config.agent_id,
        token: credentials.token,
        onMessage: (data) => {
          if (data.type === 'text' && data.content) {
            process.stdout.write(data.content);
          } else if (data.type === 'tool_use') {
            console.log(`\n🛠️  [${data.tool || data.tool_name}] ${JSON.stringify(data.input || data.tool_input || {}).substring(0, 100)}`);
          } else if (data.type === 'tool_result') {
            const result = data.result || data.content || '';
            const resultStr = typeof result === 'string' ? result : JSON.stringify(result);
            const preview = resultStr.substring(0, 200);
            console.log(`\n✅ [Result] ${preview}${resultStr.length > 200 ? '...' : ''}`);
          } else if (data.type === 'error') {
            console.error(`\n❌ Error: ${data.error}`);
          } else if (data.type === 'result') {
            if (data.result) {
              console.log(`\n🎯 [Final] ${data.result}`);
            }
            if (data.duration_ms) {
              console.log(`⏱️  Duration: ${(data.duration_ms / 1000).toFixed(2)}s`);
            }
            if (data.cost_usd) {
              console.log(`💰 Cost: $${data.cost_usd.toFixed(4)}`);
            }
          }
        },
        onError: (error) => {
          console.error(`\n❌ Execution error: ${error.message}`);
        },
      });
      
      console.log('\n');
      console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      console.log('');
      console.log('💡 After planning: Run "atris do" to execute tasks');
      console.log('');
    } catch (error) {
      console.error(`\n✗ Agent execution failed: ${error.message}`);
      throw error;
    }
  }
  // Prompt mode continues with existing output (already logged above)
}

async function doAtris() {
  const { loadConfig } = require('../utils/config');
  const { loadCredentials } = require('../utils/auth');
  const { executeCodeExecution } = require('../utils/claude_sdk');
  const args = process.argv.slice(3);
  const executeFlag = args.includes('--execute');
  const showFull = args.includes('--full') || args.includes('--verbose');
  
  const config = loadConfig();
  const executionMode = executeFlag ? 'agent' : (config.execution_mode || 'prompt');
  
  const cwd = process.cwd();
  const targetDir = path.join(cwd, 'atris');
  const executorFile = path.join(targetDir, 'agent_team', 'executor.md');

  if (!fs.existsSync(executorFile)) {
    console.log('✗ executor.md not found. Run "atris init" first.');
    process.exit(1);
  }

  // Load project profile for context
  let context = 'ROOT';
  let profile = null;
  const profileFile = path.join(targetDir, '.project-profile.json');
  if (fs.existsSync(profileFile)) {
    try {
      profile = JSON.parse(fs.readFileSync(profileFile, 'utf8'));
      // Use profile type as context (e.g., 'nodejs', 'python', 'knowledge-base')
      context = profile.type.toUpperCase();
      if (profile.framework !== 'none') {
        context += `/${profile.framework.toUpperCase()}`;
      }
    } catch (e) {
      // Fallback to ROOT if profile parse fails
      context = 'ROOT';
    }
  }
  
  // Load executor spec
  const executorSpec = fs.readFileSync(executorFile, 'utf8');

  // Load PERSONA.md
  const personaFile = path.join(targetDir, 'PERSONA.md');
  let persona = '';
  if (fs.existsSync(personaFile)) {
    persona = fs.readFileSync(personaFile, 'utf8');
  }

  // Reference MAP.md (agents read on-demand)
  const mapFile = path.join(targetDir, 'MAP.md');
  const mapPath = fs.existsSync(mapFile) ? path.relative(process.cwd(), mapFile) : null;
  const mapIsPlaceholder = (() => {
    if (!fs.existsSync(mapFile)) return false;
    try {
      const content = fs.readFileSync(mapFile, 'utf8').toLowerCase();
      return content.includes('generated by your ai agent after reading atris.md')
        || content.includes('run your ai agent with atris.md to populate this file');
    } catch {
      return false;
    }
  })();

  // Load tasks from TODO.md (generic - no hardcoded paths, legacy TASK_CONTEXTS.md supported)
  let tasksContent = '';
  let taskSource = '';
  const todoFile = path.join(targetDir, 'TODO.md');
  const legacyTaskContextsFile = path.join(targetDir, 'TASK_CONTEXTS.md');
  const taskFilePath = fs.existsSync(todoFile)
    ? todoFile
    : (fs.existsSync(legacyTaskContextsFile) ? legacyTaskContextsFile : null);
  if (taskFilePath) {
    tasksContent = fs.readFileSync(taskFilePath, 'utf8');
    taskSource = fs.existsSync(todoFile) ? 'atris/TODO.md' : 'atris/TASK_CONTEXTS.md';
  }

  if (!taskSource) {
    taskSource = 'atris/TODO.md';
  }
  
  // Extract tasks from TODO.md (no tag filtering - all tasks available)
  const taskTag = '';
  let filteredTasks = '';
  if (taskTag && tasksContent) {
    const taskLines = tasksContent.split('\n');
    let inTasksSection = false;
    let currentTask = [];
    for (const line of taskLines) {
      if (line.includes('<tasks>')) {
        inTasksSection = true;
        continue;
      }
      if (line.includes('</tasks>')) {
        inTasksSection = false;
        if (currentTask.length > 0) {
          filteredTasks += currentTask.join('\n') + '\n\n';
        }
        currentTask = [];
        continue;
      }
      if (inTasksSection && line.trim()) {
        if (line.includes(taskTag)) {
          currentTask = [line];
        } else if (currentTask.length > 0) {
          currentTask.push(line);
        }
      }
    }
    if (currentTask.length > 0) {
      filteredTasks += currentTask.join('\n') + '\n';
    }
  } else {
    filteredTasks = tasksContent;
  }
  
  // Load TODO.md content (using existing task file variable)
  let taskContexts = '';
  if (taskFilePath && fs.existsSync(taskFilePath)) {
    taskContexts = fs.readFileSync(taskFilePath, 'utf8');
  }

  const executorPath = path.relative(process.cwd(), executorFile);
  const personaFileRef = fs.existsSync(personaFile) ? path.relative(process.cwd(), personaFile) : null;
  const taskSourcePath = taskFilePath ? path.relative(process.cwd(), taskFilePath) : null;
  const featuresReadmePath = path.join(targetDir, 'features', 'README.md');
  const featuresReadmeRef = fs.existsSync(featuresReadmePath) ? path.relative(process.cwd(), featuresReadmePath) : null;

  let featureBuildPlanRefs = [];
  const featuresDir = path.join(targetDir, 'features');
  if (fs.existsSync(featuresDir)) {
    try {
      featureBuildPlanRefs = fs
        .readdirSync(featuresDir)
        .filter((name) => !name.startsWith('_'))
        .filter((name) => {
          const full = path.join(featuresDir, name);
          try {
            return fs.statSync(full).isDirectory();
          } catch {
            return false;
          }
        })
        .map((name) => path.join(featuresDir, name, 'build.md'))
        .filter((buildPath) => fs.existsSync(buildPath))
        .map((buildPath) => path.relative(process.cwd(), buildPath));
    } catch {
      featureBuildPlanRefs = [];
    }
  }

  let workspaceSummary = null;
  try {
    const { loadContext } = require('../lib/state-detection');
    workspaceSummary = loadContext(cwd);
  } catch {
    workspaceSummary = null;
  }
  
  // Prompt-mode output (keep concise by default)
  console.log('');
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│ Atris Do — Executor Agent Activated                         │');
  console.log(`│ Context: ${context}                                           │`);
  console.log('└─────────────────────────────────────────────────────────────┘');
  console.log('');

  console.log('📁 CONTEXT FILES (agent should read):');
  console.log(`- Executor spec: ${executorPath}`);
  console.log(`- Persona: ${personaFileRef || 'atris/PERSONA.md (missing)'}`);
  const mapDisplay = mapPath
    ? `${mapPath}${mapIsPlaceholder ? ' (placeholder — generate first)' : ''}`
    : 'atris/MAP.md (missing)';
  console.log(`- MAP: ${mapDisplay}`);
  console.log(`- TODO: ${taskSourcePath || 'atris/TODO.md (missing)'}`);
  console.log(`- Features index: ${featuresReadmeRef || 'atris/features/README.md (missing)'}`);
  console.log('');

  const backlogCount = workspaceSummary && Array.isArray(workspaceSummary.backlogTasks)
    ? workspaceSummary.backlogTasks.length
    : 0;
  const inProgressCount = workspaceSummary && Array.isArray(workspaceSummary.inProgressFeatures)
    ? workspaceSummary.inProgressFeatures.length
    : 0;

  if (inProgressCount > 0) {
    console.log(`🔨 In-progress features: ${workspaceSummary.inProgressFeatures.join(', ')}`);
  }
  console.log(`🧱 Feature build plans found: ${featureBuildPlanRefs.length}`);
  if (featureBuildPlanRefs.length > 0) {
    featureBuildPlanRefs.slice(0, 3).forEach((ref) => console.log(`- ${ref}`));
    if (featureBuildPlanRefs.length > 3) {
      console.log(`- ... (+${featureBuildPlanRefs.length - 3} more)`);
    }
  }
  console.log(`📋 Backlog tasks: ${backlogCount}`);
  console.log('');

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📋 COPY/PASTE PROMPT FOR YOUR CODING AGENT:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('');
  console.log('You are the Executor.');
  console.log('');
  console.log('Read these files:');
  console.log(`- ${executorPath}`);
  if (personaFileRef) console.log(`- ${personaFileRef}`);
  if (mapPath) console.log(`- ${mapPath}`);
  if (taskSourcePath) console.log(`- ${taskSourcePath}`);
  if (featuresReadmeRef) console.log(`- ${featuresReadmeRef}`);
  console.log('');
  if (!mapPath || mapIsPlaceholder) {
    console.log('Note: If `atris/MAP.md` is missing or placeholder, generate it from `atris/atris.md` before navigating the codebase.');
    console.log('');
  }
  console.log('Workflow:');
  console.log('1) If a feature has `build.md`, execute it step-by-step (no redesign).');
  console.log('2) Otherwise, pull the next item from TODO Backlog → In Progress → Completed.');
  console.log('3) Run tests as you go; stop when tasks are done.');
  console.log('');
  console.log('⛔ Do NOT plan — just execute what\'s written.');
  console.log('');

  if (showFull) {
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('📎 APPENDIX (full context dumps):');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    if (persona) {
      console.log('👤 PERSONA.md (full):');
      console.log('─────────────────────────────────────────────────────────────');
      console.log(persona);
      console.log('');
    }

    console.log('🔧 EXECUTOR SPEC (full):');
    console.log('─────────────────────────────────────────────────────────────');
    console.log(executorSpec);
    console.log('');

    if (filteredTasks) {
      console.log(`📋 TASKS TO EXECUTE (full, from ${taskSource}):`);
      console.log('─────────────────────────────────────────────────────────────');
      console.log(filteredTasks);
      console.log('');
    }

    if (taskContexts && taskContexts.trim()) {
      console.log('📝 TODO.md (full):');
      console.log('─────────────────────────────────────────────────────────────');
      console.log(taskContexts);
      console.log('');
    }
  }

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('💡 Next: Run "atris review" after execution');
  if (!showFull) {
    console.log('   Tip: `atris do --full` prints full spec/context for copy/paste.');
  }
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('');
  
  // Check execution mode
  if (executionMode === 'agent') {
    // Agent mode: execute via backend API
    if (!config.agent_id) {
      throw new Error('No agent selected. Run "atris agent" first.');
    }
    const credentials = loadCredentials();
    if (!credentials || !credentials.token) {
      throw new Error('Not logged in. Run "atris login" first.');
    }

    // Build system prompt
    let systemPrompt = '';
    if (executorSpec) {
      systemPrompt += executorSpec + '\n\n';
    }
    if (persona) {
      systemPrompt += '## PERSONA.md\n' + persona + '\n\n';
    }
    if (mapPath) {
      systemPrompt += `## MAP.md\nRead this file for file:line references: ${mapPath}\n\n`;
    }
    if (profile) {
      systemPrompt += `## PROJECT CONTEXT\nType: ${context}\nProfile: ${JSON.stringify(profile, null, 2)}\n\n`;
    }

    // Build user prompt with context
    let userPrompt = `⚠️ CRITICAL: Execute tasks NOW. Use file tools to edit code, terminal to run commands.\n\n`;
    userPrompt += `You are the Executor. Get it done, precisely, following instructions perfectly.\n\n`;
    
    if (filteredTasks) {
      userPrompt += `## TASKS TO EXECUTE (from ${taskSource}):\n${filteredTasks}\n\n`;
    } else {
      userPrompt += `## TASKS TO EXECUTE:\n(No tasks found - check TODO.md)\n\n`;
    }
    
    if (taskContexts) {
      userPrompt += `## TODO.md (Additional Context):\n${taskContexts}\n\n`;
    }
    
    userPrompt += `Your process (EXECUTE these steps):\n`;
    userPrompt += `1. Read tasks from TODO.md (shown above)\n`;
    userPrompt += `2. For each task: Show ASCII visualization first (especially complex changes)\n`;
    userPrompt += `3. Execute task: Use file edit tools, terminal commands, etc.\n`;
    userPrompt += `4. After completion: Move task to TODO.md <completed> section\n`;
    userPrompt += `5. Follow PERSONA.md for communication style\n`;
    userPrompt += `6. Use MAP.md to navigate codebase\n\n`;
    userPrompt += `DO NOT just describe what you would do - actually edit files and execute commands!\n`;
    userPrompt += `Context: ${context}\n`;
    userPrompt += `Start executing tasks now.`;

    console.log('');
    console.log('🤖 AGENT MODE: Executing via backend API...');
    console.log('');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    // Execute via API
    try {
      await executeCodeExecution({
        prompt: userPrompt,
        allowedTools: ['Read', 'Write', 'Edit', 'Bash'], // Executor needs all tools
        permissionMode: 'default',
        maxTurns: 20,
        systemPrompt,
        workingDirectory: process.cwd(),
        agentId: config.agent_id,
        token: credentials.token,
        onMessage: (data) => {
          if (data.type === 'text' && data.content) {
            process.stdout.write(data.content);
          } else if (data.type === 'tool_use') {
            console.log(`\n🛠️  [${data.tool || data.tool_name}] ${JSON.stringify(data.input || data.tool_input || {}).substring(0, 100)}`);
          } else if (data.type === 'tool_result') {
            const result = data.result || data.content || '';
            const resultStr = typeof result === 'string' ? result : JSON.stringify(result);
            const preview = resultStr.substring(0, 200);
            console.log(`\n✅ [Result] ${preview}${resultStr.length > 200 ? '...' : ''}`);
          } else if (data.type === 'error') {
            console.error(`\n❌ Error: ${data.error}`);
          } else if (data.type === 'result') {
            if (data.result) {
              console.log(`\n🎯 [Final] ${data.result}`);
            }
            if (data.duration_ms) {
              console.log(`⏱️  Duration: ${(data.duration_ms / 1000).toFixed(2)}s`);
            }
            if (data.cost_usd) {
              console.log(`💰 Cost: $${data.cost_usd.toFixed(4)}`);
            }
          }
        },
        onError: (error) => {
          console.error(`\n❌ Execution error: ${error.message}`);
        },
      });
      
      console.log('\n');
      console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      console.log('');
    } catch (error) {
      console.error(`\n✗ Agent execution failed: ${error.message}`);
      throw error;
    }
  }
  // Prompt mode continues with existing output (already logged above)
}

async function reviewAtris() {
  const { loadConfig } = require('../utils/config');
  const { loadCredentials } = require('../utils/auth');
  const { executeCodeExecution } = require('../utils/claude_sdk');
  const args = process.argv.slice(3);
  const executeFlag = args.includes('--execute');
  const showFull = args.includes('--full') || args.includes('--verbose');
  
  const config = loadConfig();
  const executionMode = executeFlag ? 'agent' : (config.execution_mode || 'prompt');
  
  const targetDir = path.join(process.cwd(), 'atris');
  const validatorFile = path.join(targetDir, 'agent_team', 'validator.md');

  if (!fs.existsSync(validatorFile)) {
    console.log('✗ validator.md not found. Run "atris init" first.');
    process.exit(1);
  }

  // Read validator.md
  const validatorSpec = fs.readFileSync(validatorFile, 'utf8');

  // Read project-specific testing guide if it exists (optional - projects can add their own)
  // Checks common locations: root, backend/, atris/ directories
  let testingGuide = '';
  let testingGuidePath = null;
  const possiblePaths = [
    path.join(process.cwd(), 'AGENT_TESTING_GUIDE.md'),
    path.join(process.cwd(), 'TESTING_GUIDE.md'),
    path.join(process.cwd(), 'atris', 'TESTING_GUIDE.md'),
  ];
  for (const guidePath of possiblePaths) {
    if (fs.existsSync(guidePath)) {
      testingGuide = fs.readFileSync(guidePath, 'utf8');
      testingGuidePath = guidePath;
      break;
    }
  }

  // Read TODO.md (or legacy TASK_CONTEXTS.md)
  const todoFile = path.join(targetDir, 'TODO.md');
  const legacyTaskContextsFile = path.join(targetDir, 'TASK_CONTEXTS.md');
  let taskContexts = '';
  const taskFilePath = fs.existsSync(todoFile)
    ? todoFile
    : (fs.existsSync(legacyTaskContextsFile) ? legacyTaskContextsFile : null);
  if (taskFilePath) {
    taskContexts = fs.readFileSync(taskFilePath, 'utf8');
  }

  // Read journal for timestamp context (History)
  const { logFile, dateFormatted } = getLogPath();
  let journalHistory = '';
  
  // Load today's log
  if (fs.existsSync(logFile)) {
    journalHistory += `## TODAY (${dateFormatted}):\n` + fs.readFileSync(logFile, 'utf8') + '\n\n';
  }

  // Load previous 3 days of logs for Drift Detection
  // (We need to find them in the logs directory)
  const targetLogsDir = path.join(targetDir, 'logs');
  if (fs.existsSync(targetLogsDir)) {
    // Simple recursive search for last 3 .md files
    const allLogs = [];
    const yearDirs = fs.readdirSync(targetLogsDir).filter(d => /^\d{4}$/.test(d));
    for (const year of yearDirs) {
      const yearPath = path.join(targetLogsDir, year);
      if (fs.statSync(yearPath).isDirectory()) {
        const files = fs.readdirSync(yearPath).filter(f => f.endsWith('.md') && f !== path.basename(logFile));
        files.forEach(f => allLogs.push(path.join(yearPath, f)));
      }
    }
    // Sort desc, take top 3
    allLogs.sort().reverse();
    const recentLogs = allLogs.slice(0, 3);
    
    if (recentLogs.length > 0) {
      journalHistory += `## RECENT HISTORY (Drift Check):\n`;
      for (const log of recentLogs) {
        journalHistory += `--- ${path.basename(log)} ---\n`;
        journalHistory += fs.readFileSync(log, 'utf8').substring(0, 1000) + '\n... (truncated)\n\n'; // Read first 1kb
      }
    }
  }

  const mapFile = path.join(targetDir, 'MAP.md');
  const mapPath = fs.existsSync(mapFile) ? path.relative(process.cwd(), mapFile) : null;
  const mapIsPlaceholder = (() => {
    if (!fs.existsSync(mapFile)) return false;
    try {
      const content = fs.readFileSync(mapFile, 'utf8').toLowerCase();
      return content.includes('generated by your ai agent after reading atris.md')
        || content.includes('run your ai agent with atris.md to populate this file');
    } catch {
      return false;
    }
  })();

  const validatorPath = path.relative(process.cwd(), validatorFile);
  const todoPathRef = taskFilePath ? path.relative(process.cwd(), taskFilePath) : null;
  const journalPathRef = path.relative(process.cwd(), logFile);
  const personaPath = path.join(targetDir, 'PERSONA.md');
  const personaRef = fs.existsSync(personaPath) ? path.relative(process.cwd(), personaPath) : null;
  const testingGuideRef = testingGuidePath ? path.relative(process.cwd(), testingGuidePath) : null;

  const featuresReadmePath = path.join(targetDir, 'features', 'README.md');
  const featuresReadmeRef = fs.existsSync(featuresReadmePath) ? path.relative(process.cwd(), featuresReadmePath) : null;

  let featureValidateRefs = [];
  const featuresDir = path.join(targetDir, 'features');
  if (fs.existsSync(featuresDir)) {
    try {
      featureValidateRefs = fs
        .readdirSync(featuresDir)
        .filter((name) => !name.startsWith('_'))
        .filter((name) => {
          const full = path.join(featuresDir, name);
          try {
            return fs.statSync(full).isDirectory();
          } catch {
            return false;
          }
        })
        .map((name) => path.join(featuresDir, name, 'validate.md'))
        .filter((validatePath) => fs.existsSync(validatePath))
        .map((validatePath) => path.relative(process.cwd(), validatePath));
    } catch {
      featureValidateRefs = [];
    }
  }

  console.log('');
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│ Atris Review — Validator Agent Activated                    │');
  console.log('└─────────────────────────────────────────────────────────────┘');
  console.log('');

  console.log('📁 CONTEXT FILES (agent should read):');
  console.log(`- Validator spec: ${validatorPath}`);
  console.log(`- Testing guide: ${testingGuideRef || '(none found)'}`);
  console.log(`- Persona: ${personaRef || 'atris/PERSONA.md (missing)'}`);
  const mapDisplay = mapPath
    ? `${mapPath}${mapIsPlaceholder ? ' (placeholder — generate first)' : ''}`
    : 'atris/MAP.md (missing)';
  console.log(`- MAP: ${mapDisplay}`);
  console.log(`- TODO: ${todoPathRef || 'atris/TODO.md (missing)'}`);
  console.log(`- Journal (today): ${journalPathRef}`);
  console.log(`- Features index: ${featuresReadmeRef || 'atris/features/README.md (missing)'}`);
  console.log('');

  console.log(`🧪 Feature validate scripts found: ${featureValidateRefs.length}`);
  if (featureValidateRefs.length > 0) {
    featureValidateRefs.slice(0, 3).forEach((ref) => console.log(`- ${ref}`));
    if (featureValidateRefs.length > 3) {
      console.log(`- ... (+${featureValidateRefs.length - 3} more)`);
    }
  }
  console.log('');

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📋 COPY/PASTE PROMPT FOR YOUR CODING AGENT:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('');
  console.log('You are the Validator.');
  console.log('');
  console.log('Read these files:');
  console.log(`- ${validatorPath}`);
  if (testingGuideRef) console.log(`- ${testingGuideRef}`);
  if (personaRef) console.log(`- ${personaRef}`);
  if (mapPath) console.log(`- ${mapPath}`);
  if (todoPathRef) console.log(`- ${todoPathRef}`);
  console.log(`- ${journalPathRef}`);
  if (featuresReadmeRef) console.log(`- ${featuresReadmeRef}`);
  console.log('');
  if (!mapPath || mapIsPlaceholder) {
    console.log('Note: If `atris/MAP.md` is missing or placeholder, generate it from `atris/atris.md` before validating file:line references.');
    console.log('');
  }
  console.log('Workflow:');
  console.log('1) Run the project test suite (follow TESTING_GUIDE if present).');
  console.log('2) Execute any `atris/features/*/validate.md` scripts; if a step fails, fix + rerun.');
  console.log('3) Update TODO.md + today\'s journal with results; propose tool upgrades if drift repeats.');
  console.log('');
  console.log('Done when: ✅ All good. Ready for human testing.');
  console.log('');

  if (showFull) {
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('📎 APPENDIX (full context dumps):');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    console.log('📋 VALIDATOR SPEC (full):');
    console.log('─────────────────────────────────────────────────────────────');
    console.log(validatorSpec);
    console.log('');

    if (testingGuide) {
      console.log('🧪 TESTING GUIDE (full):');
      console.log('─────────────────────────────────────────────────────────────');
      console.log(testingGuide);
      console.log('');
    }

    if (taskContexts) {
      console.log('📝 TODO.md (full):');
      console.log('─────────────────────────────────────────────────────────────');
      console.log(taskContexts);
      console.log('');
    }
  }

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('💡 Next: Run "atris do" to fix any issues, then "atris review" again');
  if (!showFull) {
    console.log('   Tip: `atris review --full` prints full spec/context for copy/paste.');
  }
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('');
  
  // Check execution mode
  if (executionMode === 'agent') {
    // Agent mode: execute via backend API
    if (!config.agent_id) {
      throw new Error('No agent selected. Run "atris agent" first.');
    }
    const credentials = loadCredentials();
    if (!credentials || !credentials.token) {
      throw new Error('Not logged in. Run "atris login" first.');
    }

    // Build system prompt
    let systemPrompt = '';
    if (validatorSpec) {
      systemPrompt += validatorSpec + '\n\n';
    }
    if (testingGuide) {
      systemPrompt += '## TESTING GUIDE\n' + testingGuide + '\n\n';
    }
    
    const personaFile = path.join(targetDir, 'PERSONA.md');
    if (fs.existsSync(personaFile)) {
      systemPrompt += '## PERSONA.md\n' + fs.readFileSync(personaFile, 'utf8') + '\n\n';
    }
    
    if (mapPath) {
      systemPrompt += `## MAP.md\nRead this file for file:line references: ${mapPath}\n\n`;
    }

    // Build user prompt with context
    let userPrompt = `You are the Validator. Auto-activated after "atris do" completes.\n\n`;
    userPrompt += `Validation Loop:\n`;
    userPrompt += `  1. Ultrathink (say "ultrathink", think 3 times)\n`;
    userPrompt += `  2. Check requirements → build → edge cases → errors → integration\n`;
    userPrompt += `  3. Run tests (unit, integration, linting, type checking)\n`;
    userPrompt += `  4. Detect Drift: Scan the Journal History below. Do you see the same friction 2x?\n`;
    userPrompt += `  5. If issues found: report → "atris do" fixes → "atris review" again\n`;
    userPrompt += `  6. Repeat until: "✅ All good. Ready for human testing."\n\n`;
    
    if (taskContexts) {
      userPrompt += `## TODO.md:\n${taskContexts}\n\n`;
    }

    if (journalHistory) {
      userPrompt += `## JOURNAL HISTORY (For Evolution/Drift Check):\n${journalHistory}\n\n`;
    }
    
    userPrompt += `Your job:\n`;
    userPrompt += `  • Verify everything works\n`;
    userPrompt += `  • Test thoroughly (unless user says no)\n`;
    userPrompt += `  • Update docs if needed (MAP.md, TODO.md)\n`;
    userPrompt += `  • Clean TODO.md (move completed tasks to Completed section, then delete)\n`;
    userPrompt += `  • Extract learnings for journal\n`;
    userPrompt += `  • EVOLUTION: If you see drift in the logs, propose a tool upgrade.\n\n`;
    userPrompt += `The cycle: do → review → [issues] → do → review → ✅ Ready\n`;
    userPrompt += `Start validating now. Read files, run tests, verify implementation.`;

    console.log('');
    console.log('🤖 AGENT MODE: Executing via backend API...');
    console.log('');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    // Execute via API
    try {
      await executeCodeExecution({
        prompt: userPrompt,
        allowedTools: ['Read', 'Write', 'Edit', 'Bash'], // Validator needs to read, test, update docs
        permissionMode: 'default',
        maxTurns: 15,
        systemPrompt,
        workingDirectory: process.cwd(),
        agentId: config.agent_id,
        token: credentials.token,
        onMessage: (data) => {
          if (data.type === 'text' && data.content) {
            process.stdout.write(data.content);
          } else if (data.type === 'tool_use') {
            console.log(`\n🛠️  [${data.tool || data.tool_name}] ${JSON.stringify(data.input || data.tool_input || {}).substring(0, 100)}`);
          } else if (data.type === 'tool_result') {
            const result = data.result || data.content || '';
            const resultStr = typeof result === 'string' ? result : JSON.stringify(result);
            const preview = resultStr.substring(0, 200);
            console.log(`\n✅ [Result] ${preview}${resultStr.length > 200 ? '...' : ''}`);
          } else if (data.type === 'error') {
            console.error(`\n❌ Error: ${data.error}`);
          } else if (data.type === 'result') {
            if (data.result) {
              console.log(`\n🎯 [Final] ${data.result}`);
            }
            if (data.duration_ms) {
              console.log(`⏱️  Duration: ${(data.duration_ms / 1000).toFixed(2)}s`);
            }
            if (data.cost_usd) {
              console.log(`💰 Cost: $${data.cost_usd.toFixed(4)}`);
            }
          }
        },
        onError: (error) => {
          console.error(`\n❌ Execution error: ${error.message}`);
        },
      });
      
      console.log('\n');
      console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      console.log('');
    } catch (error) {
      console.error(`\n✗ Agent execution failed: ${error.message}`);
      throw error;
    }
  }
  // Prompt mode continues with existing output (already logged above)

  // Handoff prompt: suggest writing handoff if completions exist today
  if (fs.existsSync(logFile)) {
    const journalContent = fs.readFileSync(logFile, 'utf8');
    const hasCompletions = /## Completed ✅[\s\S]*?- \*\*C\d+:/.test(journalContent);
    const hasHandoff = /## Handoff[\s\S]*?\*\*Context:\*\*/.test(journalContent);

    if (hasCompletions && !hasHandoff) {
      console.log('');
      console.log('┌─────────────────────────────────────────────────────────────┐');
      console.log('│ 📝 SESSION HANDOFF                                          │');
      console.log('├─────────────────────────────────────────────────────────────┤');
      console.log('│ You have completions today. Write a handoff for next session│');
      console.log('│                                                             │');
      console.log('│ Add to ## Handoff section in today\'s journal:               │');
      console.log('│   **Context:** [2 lines - what was accomplished]            │');
      console.log('│   **Blockers:** [any issues hit, or "none"]                 │');
      console.log('│   **Next:** [1 clear action for next session]               │');
      console.log('│   **Learned:** [key insight or pattern discovered]          │');
      console.log('└─────────────────────────────────────────────────────────────┘');
      console.log('');
    }
  }

  // Prompt for learnings
  console.log('');
  console.log('┌─────────────────────────────────────────────────────────────┐');
  console.log('│ 💡 Any learnings?                                           │');
  console.log('│ (Enter insight, or press Enter to skip)                     │');
  console.log('└─────────────────────────────────────────────────────────────┘');

  const readline = require('readline');
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise((resolve) => {
    rl.question('> ', (answer) => {
      rl.close();

      if (answer && answer.trim()) {
        // Log to journal ## Notes section
        const { logFile } = getLogPath();
        if (fs.existsSync(logFile)) {
          let journalContent = fs.readFileSync(logFile, 'utf8');
          const timestamp = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false });
          const learning = `- ${timestamp} — ${answer.trim()}`;

          // Find or create ## Notes section
          if (journalContent.includes('## Notes')) {
            journalContent = journalContent.replace(/## Notes\n/, `## Notes\n${learning}\n`);
          } else {
            journalContent += `\n## Notes\n${learning}\n`;
          }

          fs.writeFileSync(logFile, journalContent);
          console.log('');
          console.log(`✓ Logged to journal: ${learning}`);
        }
      }

      console.log('');
      resolve();
    });
  });
}


module.exports = {
  planAtris,
  doAtris,
  reviewAtris
};
